<template>
    <nuxt />
</template>

<style>
html {
  font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI',
    Roboto, 'Helvetica Neue', Arial, sans-serif;
  font-size: 16px;
  word-spacing: 1px;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
}

.title-font {
    font-family: Patua One,Helvetica,Arial,sans-serif;
}

.bg-dark {
    background-color: #153A59 !important;
}
.color-white {
    color: #fff;
}
.py-85 {
    padding-top: 85px;
    padding-bottom: 85px;
}
h1.small, h2.small {
    font-size: 42px;
    line-height: 52px;
    font-weight: 300;
}

.section-title-main {
    font-size: 2em;
    font-weight: 300;
    line-height: 1.2;
}

.section-title {
    font-size: 2.8em;
    font-weight: 300;
    line-height: 1.2;
}

.subheading {
    font-size: 1.4em;
    font-weight: 300;
    line-height: 1.2;
}


/* Custom scrollbar */

::-webkit-scrollbar {
    width: 12px;
}

/* Track */
::-webkit-scrollbar-track {
    background: hsla(337, 88%, 9%, 0.95);
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: #343a40;
}

::-webkit-scrollbar-thumb:window-inactive {
    background: hsla(337, 88%, 9%, 0.95);
}

/* Animation  */

.fade-in {
    -webkit-animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

.fade-in2 {
    -webkit-animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.2s both;
    animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.2s both;
}

.fade-in3 {
    -webkit-animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.4s both;
    animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.4s both;
}

.fade-in4 {
    -webkit-animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.6s both;
    animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.6s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-6-19 15:0:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
    0% {
        opacity: 0;
    }

    100% {
        opacity: 1;
    }
}

@keyframes fade-in {
    0% {
        opacity: 0;
    }

    100% {
        opacity: 1;
    }
}
</style>